central:
  reports:
    datastores:
      - artifact://k1LoW/expand
      - artifact://k1LoW/grpcstub
      - artifact://k1LoW/ghfs
      - artifact://k1LoW/ghput
      - artifact://k1LoW/httpstub
      - artifact://k1LoW/ndiag
      - artifact://k1LoW/octocov
      - artifact://k1LoW/runn
      - artifact://k1LoW/smtptest
      - artifact://k1LoW/stopw
      - artifact://k1LoW/tbls
      - artifact://k1LoW/tcpdp
  badges:
    datastores:
      - local://badges
  push:
    enable: true
